server:
  port: 8081

#Disable Thymeleaf caching for development, should be enabled for production
spring:
  thymeleaf:
    cache: false

#Keycloak Configuration
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: oab
  resource: beer-web
  public-client: true
  principal-attribute: name